-- Initial Schema Create for SteamAccountTracker

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Passwordhash NVARCHAR(MAX) NOT NULL,
    Session_Id UNIQUEIDENTIFIER NULL,
    Session_exp DATETIME2 NULL
);

CREATE TABLE SteamAccounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SteamId64 NVARCHAR(17) NOT NULL UNIQUE
);

CREATE TABLE UserSteamAccounts (
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    SteamAccountId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SteamAccounts(Id) ON DELETE CASCADE,
    PRIMARY KEY (UserId, SteamAccountId)
);
