ALTER TABLE Users ADD
    EmailNotificationsEnabled BIT NOT NULL DEFAULT 1,
    DiscordNotificationsEnabled BIT NOT NULL DEFAULT 1;

CREATE TABLE UserWebhooks (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Name NVARCHAR(100) NOT NULL,
    WebhookUrl NVARCHAR(1000) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

